#!/usr/bin/env bash
#  Bash script that displays the content of the file /etc/passwd
#  the script should display :
#	- username
#	- user id
#	- Home directory path for the user

while IFS=":" read -r -a fields
do
	echo "${fields[0]}:${fields[2]}:${fields[5]}"
done < /etc/passwd
