#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

HOUR=0

while [ $HOUR -le 12 ]; do

	echo "Hour: ${HOUR}"
	MINUTE=1
	while [ $MINUTE -lt 60 ]; do

		echo "${MINUTE}"
		((MINUTE++))
	done
	((HOUR++))
done
