#!/usr/bin/env bash
# Displays information about the file `school`.

FILE=school

if [ -e ${FILE} ]; then
	echo "${FILE} file exists"
	[ -s "${FILE}" ] && echo "${FILE} file is not empty" || echo "${FILE} file is empty"
	[ ! -d ${FILE} ] && echo "${FILE} is a regular file"
else
	echo "${FILE} file does not exist"
fi
